CREATE PROCEDURE [remuneraciones].[__SPRM_CargoMod_ValidaCadenaObservaciones](
	@USUARIOCREADOR VARCHAR(MAX),
	@CODIGOSOLICITUD VARCHAR(MAX),
	@OBSERVACIONES VARCHAR(MAX),
	@CODE VARCHAR(MAX) OUTPUT,
	@MESSAGE VARCHAR(MAX) OUTPUT
)
AS
	
	BEGIN TRY
		
		BEGIN TRANSACTION

			DECLARE @__CADENAOBSERVACIONES VARCHAR(MAX)
			
			SELECT @__CADENAOBSERVACIONES = VHE.Observaciones
			       FROM [remuneraciones].[View_HeaderEstructura] VHE
				   WHERE VHE.CodigoCargoMod = @CODIGOSOLICITUD

			IF(CHARINDEX(@OBSERVACIONES, @__CADENAOBSERVACIONES) > 0)
			BEGIN
				
				SET @CODE = '200'

			END
			ELSE
			BEGIN
				
				SET @CODE = '404'

			END
			
			SET @MESSAGE = ''

		COMMIT TRANSACTION

	END TRY
	BEGIN CATCH
		
		ROLLBACK TRANSACTION

	END CATCH
