CREATE FUNCTION [remuneraciones].[FNEANI]
(
	@CODIGOCARGOMOD VARCHAR(MAX)
)
RETURNS FLOAT
AS
BEGIN
	
	DECLARE @EANIS FLOAT

	SELECT @EANIS = ISNULL(SUM(ANICM.Valor), 0)
		   FROM [remuneraciones].[RM_ANICargoMod] ANICM WITH (NOLOCK)
		   WHERE ANICM.CodigoCargoMod = @CODIGOCARGOMOD

	RETURN @EANIS

END
