
CREATE PROCEDURE [remuneraciones].[__SPRM_CargoMod_ActualizaJornadaFullTime](
	@USUARIOCREADOR VARCHAR(MAX),
	@CODIGOSOLICITUD VARCHAR(MAX),
	@HORARIOS VARCHAR(MAX),
	@HORASSEMANALES VARCHAR(MAX),
	@CODE VARCHAR(MAX) OUTPUT,
	@MESSAGE VARCHAR(MAX) OUTPUT
)
AS
	
	BEGIN TRY
		
		BEGIN TRANSACTION

			-- SI VIENE ART22 => NHORASSEMANALES ENTRA NULL => CONSIDERANDOLO COMO ARTICULO 22
			-- SI VIENE 45 => SE CONSIDERA COMO 45
			-- SI VIENE CUALQUIER OTRA HORA DIFERNETE A ART22 Y 45, SE CONSIDERA COMO OTRAS HORAS SEMANALES
			-- SI VIENE JornadaExcepcional => SE DEJARA NULL LAS HORAS SEMANALES Y ACTIVARA EL FLAG DE COLUMNA JornadaExcepcional

			DECLARE @__HORASSEMANLES FLOAT,
			        @__JORNADAEXCEPCIONAL VARCHAR(MAX)

			IF(@HORASSEMANALES = 'ART22')
			BEGIN
				SET @__HORASSEMANLES = NULL
				SET @__JORNADAEXCEPCIONAL = NULL
			END

			IF(@HORASSEMANALES = 'JornadaExcepcional')
			BEGIN
				
				SET @__HORASSEMANLES = NULL
				SET @__JORNADAEXCEPCIONAL = 'S'

			END

			IF(@HORASSEMANALES != 'ART22' AND @HORASSEMANALES != 'JornadaExcepcional')
			BEGIN
				SET @__HORASSEMANLES = CAST(@HORASSEMANALES AS FLOAT)
				SET @__JORNADAEXCEPCIONAL = NULL
			END

			UPDATE [remuneraciones].[RM_CargosMod]
			       SET NHorasSemanales = REPLACE(@__HORASSEMANLES, ',', '.'),
				       JornadaExcepcional = @__JORNADAEXCEPCIONAL,
				       FechaUltimaActualizacion = GETDATE(),
					   UsuarioUltimaActualizacion = @USUARIOCREADOR,
					   UltimoComentario = 'Se actualiza jornada full time, en cuanto a horas semanales.'
				   WHERE CodigoCargoMod = [TW_GENERAL_TEAMWORK].[dbo].[FN_BASE64_DECODE](@CODIGOSOLICITUD)

			SET @CODE = '200'
			SET @MESSAGE = ''

		COMMIT TRANSACTION

	END TRY
	BEGIN CATCH
		
		ROLLBACK TRANSACTION

	END CATCH
