//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiniquitosV2.ServicioCorreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCorreo.IServicioCorreo")]
    public interface IServicioCorreo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandar", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarResponse")]
        bool correoTeamworkEstandar(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandar", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarResponse")]
        System.Threading.Tasks.Task<bool> correoTeamworkEstandarAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCO", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOResponse")]
        bool correoTeamworkEstandarCCO(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCO", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOResponse")]
        System.Threading.Tasks.Task<bool> correoTeamworkEstandarCCOAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoValleNevado", ReplyAction="http://tempuri.org/IServicioCorreo/correoValleNevadoResponse")]
        bool correoValleNevado(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoValleNevado", ReplyAction="http://tempuri.org/IServicioCorreo/correoValleNevadoResponse")]
        System.Threading.Tasks.Task<bool> correoValleNevadoAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOTest", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOTestResponse")]
        bool correoTeamworkEstandarCCOTest(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOTest", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkEstandarCCOTestResponse")]
        System.Threading.Tasks.Task<bool> correoTeamworkEstandarCCOTestAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarina", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaResponse")]
        bool correoMarina(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarina", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaResponse")]
        System.Threading.Tasks.Task<bool> correoMarinaAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkCCOAttachamentResponse")]
        bool correoTeamworkCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoTeamworkCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoTeamworkCCOAttachamentResponse")]
        System.Threading.Tasks.Task<bool> correoTeamworkCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoValleNevadoCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoValleNevadoCCOAttachamentResponse")]
        bool correoValleNevadoCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoValleNevadoCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoValleNevadoCCOAttachamentResponse")]
        System.Threading.Tasks.Task<bool> correoValleNevadoCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarinaCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaCCOAttachamentResponse")]
        bool correoMarinaCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarinaCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaCCOAttachamentResponse")]
        System.Threading.Tasks.Task<bool> correoMarinaCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarinaTwCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaTwCCOAttachamentResponse")]
        bool correoMarinaTwCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoMarinaTwCCOAttachament", ReplyAction="http://tempuri.org/IServicioCorreo/correoMarinaTwCCOAttachamentResponse")]
        System.Threading.Tasks.Task<bool> correoMarinaTwCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoCargoMod", ReplyAction="http://tempuri.org/IServicioCorreo/correoCargoModResponse")]
        bool correoCargoMod(string de, string clave, string para, string mensaje, string asunto, string copia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoCargoMod", ReplyAction="http://tempuri.org/IServicioCorreo/correoCargoModResponse")]
        System.Threading.Tasks.Task<bool> correoCargoModAsync(string de, string clave, string para, string mensaje, string asunto, string copia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoStandar", ReplyAction="http://tempuri.org/IServicioCorreo/correoStandarResponse")]
        bool correoStandar(string de, string clave, string para, string mensaje, string asunto, string copia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/correoStandar", ReplyAction="http://tempuri.org/IServicioCorreo/correoStandarResponse")]
        System.Threading.Tasks.Task<bool> correoStandarAsync(string de, string clave, string para, string mensaje, string asunto, string copia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCorreoChannel : FiniquitosV2.ServicioCorreo.IServicioCorreo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCorreoClient : System.ServiceModel.ClientBase<FiniquitosV2.ServicioCorreo.IServicioCorreo>, FiniquitosV2.ServicioCorreo.IServicioCorreo {
        
        public ServicioCorreoClient() {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool correoTeamworkEstandar(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority) {
            return base.Channel.correoTeamworkEstandar(de, clave, para, mensaje, asunto, cc, file, priority);
        }
        
        public System.Threading.Tasks.Task<bool> correoTeamworkEstandarAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority) {
            return base.Channel.correoTeamworkEstandarAsync(de, clave, para, mensaje, asunto, cc, file, priority);
        }
        
        public bool correoTeamworkEstandarCCO(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace) {
            return base.Channel.correoTeamworkEstandarCCO(de, clave, para, mensaje, asunto, cc, cco, file, priority, withEnlace);
        }
        
        public System.Threading.Tasks.Task<bool> correoTeamworkEstandarCCOAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace) {
            return base.Channel.correoTeamworkEstandarCCOAsync(de, clave, para, mensaje, asunto, cc, cco, file, priority, withEnlace);
        }
        
        public bool correoValleNevado(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority) {
            return base.Channel.correoValleNevado(de, clave, para, mensaje, asunto, cc, file, priority);
        }
        
        public System.Threading.Tasks.Task<bool> correoValleNevadoAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string file, string priority) {
            return base.Channel.correoValleNevadoAsync(de, clave, para, mensaje, asunto, cc, file, priority);
        }
        
        public bool correoTeamworkEstandarCCOTest(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace) {
            return base.Channel.correoTeamworkEstandarCCOTest(de, clave, para, mensaje, asunto, cc, cco, file, priority, withEnlace);
        }
        
        public System.Threading.Tasks.Task<bool> correoTeamworkEstandarCCOTestAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority, string withEnlace) {
            return base.Channel.correoTeamworkEstandarCCOTestAsync(de, clave, para, mensaje, asunto, cc, cco, file, priority, withEnlace);
        }
        
        public bool correoMarina(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority) {
            return base.Channel.correoMarina(de, clave, para, mensaje, asunto, cc, cco, file, priority);
        }
        
        public System.Threading.Tasks.Task<bool> correoMarinaAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string file, string priority) {
            return base.Channel.correoMarinaAsync(de, clave, para, mensaje, asunto, cc, cco, file, priority);
        }
        
        public bool correoTeamworkCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoTeamworkCCOAttachament(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public System.Threading.Tasks.Task<bool> correoTeamworkCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoTeamworkCCOAttachamentAsync(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public bool correoValleNevadoCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoValleNevadoCCOAttachament(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public System.Threading.Tasks.Task<bool> correoValleNevadoCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoValleNevadoCCOAttachamentAsync(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public bool correoMarinaCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoMarinaCCOAttachament(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public System.Threading.Tasks.Task<bool> correoMarinaCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoMarinaCCOAttachamentAsync(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public bool correoMarinaTwCCOAttachament(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoMarinaTwCCOAttachament(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public System.Threading.Tasks.Task<bool> correoMarinaTwCCOAttachamentAsync(string de, string clave, string para, string mensaje, string asunto, string cc, string cco, string nameFile, string priority, byte[] file, string applicationType) {
            return base.Channel.correoMarinaTwCCOAttachamentAsync(de, clave, para, mensaje, asunto, cc, cco, nameFile, priority, file, applicationType);
        }
        
        public bool correoCargoMod(string de, string clave, string para, string mensaje, string asunto, string copia) {
            return base.Channel.correoCargoMod(de, clave, para, mensaje, asunto, copia);
        }
        
        public System.Threading.Tasks.Task<bool> correoCargoModAsync(string de, string clave, string para, string mensaje, string asunto, string copia) {
            return base.Channel.correoCargoModAsync(de, clave, para, mensaje, asunto, copia);
        }
        
        public bool correoStandar(string de, string clave, string para, string mensaje, string asunto, string copia) {
            return base.Channel.correoStandar(de, clave, para, mensaje, asunto, copia);
        }
        
        public System.Threading.Tasks.Task<bool> correoStandarAsync(string de, string clave, string para, string mensaje, string asunto, string copia) {
            return base.Channel.correoStandarAsync(de, clave, para, mensaje, asunto, copia);
        }
    }
}
