CREATE FUNCTION [dbo].[FN_CONVERTMONEY]
(
	@MONTO NUMERIC
)
RETURNS VARCHAR(MAX)
AS
BEGIN
	
	DECLARE @MONEY VARCHAR(MAX)

	SET @MONEY = REPLACE(SUBSTRING(CONVERT(VARCHAR, CAST(@MONTO AS MONEY), -1), 1, CHARINDEX('.', CONVERT(VARCHAR, CAST(@MONTO AS MONEY), -1)) - 1), ',', '.')
	
	RETURN @MONEY

END
