//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiniquitosV2.ServicioAuth {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioAuth", Namespace="http://schemas.datacontract.org/2004/07/ServicioAuth")]
    [System.SerializableAttribute()]
    public partial class ServicioAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet TableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAuth.IServicioAuth")]
    public interface IServicioAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetSignIn", ReplyAction="http://tempuri.org/IServicioAuth/GetSignInResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetSignIn(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetSignIn", ReplyAction="http://tempuri.org/IServicioAuth/GetSignInResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetSignInAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetBASE64", ReplyAction="http://tempuri.org/IServicioAuth/GetBASE64Response")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetBASE64(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetBASE64", ReplyAction="http://tempuri.org/IServicioAuth/GetBASE64Response")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetBASE64Async(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPemisionSectionsAccess", ReplyAction="http://tempuri.org/IServicioAuth/GetPemisionSectionsAccessResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetPemisionSectionsAccess(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPemisionSectionsAccess", ReplyAction="http://tempuri.org/IServicioAuth/GetPemisionSectionsAccessResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPemisionSectionsAccessAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPemisionAccess", ReplyAction="http://tempuri.org/IServicioAuth/GetPemisionAccessResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetPemisionAccess(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPemisionAccess", ReplyAction="http://tempuri.org/IServicioAuth/GetPemisionAccessResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPemisionAccessAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetSectionRenderHtml", ReplyAction="http://tempuri.org/IServicioAuth/GetSectionRenderHtmlResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetSectionRenderHtml(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetSectionRenderHtml", ReplyAction="http://tempuri.org/IServicioAuth/GetSectionRenderHtmlResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetSectionRenderHtmlAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPlantillaCargaMasivaRender", ReplyAction="http://tempuri.org/IServicioAuth/GetPlantillaCargaMasivaRenderResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetPlantillaCargaMasivaRender(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetPlantillaCargaMasivaRender", ReplyAction="http://tempuri.org/IServicioAuth/GetPlantillaCargaMasivaRenderResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPlantillaCargaMasivaRenderAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetDownloadPlantillaCargaMasiva", ReplyAction="http://tempuri.org/IServicioAuth/GetDownloadPlantillaCargaMasivaResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetDownloadPlantillaCargaMasiva(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetDownloadPlantillaCargaMasiva", ReplyAction="http://tempuri.org/IServicioAuth/GetDownloadPlantillaCargaMasivaResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetDownloadPlantillaCargaMasivaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetObtenerEmpresas", ReplyAction="http://tempuri.org/IServicioAuth/GetObtenerEmpresasResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetObtenerEmpresas(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetObtenerEmpresas", ReplyAction="http://tempuri.org/IServicioAuth/GetObtenerEmpresasResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetObtenerEmpresasAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetBarcodes", ReplyAction="http://tempuri.org/IServicioAuth/GetBarcodesResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth GetBarcodes(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/GetBarcodes", ReplyAction="http://tempuri.org/IServicioAuth/GetBarcodesResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetBarcodesAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetEnrolarColaborador", ReplyAction="http://tempuri.org/IServicioAuth/SetEnrolarColaboradorResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth SetEnrolarColaborador(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetEnrolarColaborador", ReplyAction="http://tempuri.org/IServicioAuth/SetEnrolarColaboradorResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetEnrolarColaboradorAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetControlErroresSistemas", ReplyAction="http://tempuri.org/IServicioAuth/SetControlErroresSistemasResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth SetControlErroresSistemas(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetControlErroresSistemas", ReplyAction="http://tempuri.org/IServicioAuth/SetControlErroresSistemasResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetControlErroresSistemasAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetBatchChangeContrato", ReplyAction="http://tempuri.org/IServicioAuth/SetBatchChangeContratoResponse")]
        FiniquitosV2.ServicioAuth.ServicioAuth SetBatchChangeContrato(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuth/SetBatchChangeContrato", ReplyAction="http://tempuri.org/IServicioAuth/SetBatchChangeContratoResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetBatchChangeContratoAsync(string[] Parametros, string[] valores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAuthChannel : FiniquitosV2.ServicioAuth.IServicioAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAuthClient : System.ServiceModel.ClientBase<FiniquitosV2.ServicioAuth.IServicioAuth>, FiniquitosV2.ServicioAuth.IServicioAuth {
        
        public ServicioAuthClient() {
        }
        
        public ServicioAuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetSignIn(string[] Parametros, string[] valores) {
            return base.Channel.GetSignIn(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetSignInAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetSignInAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetBASE64(string[] Parametros, string[] valores) {
            return base.Channel.GetBASE64(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetBASE64Async(string[] Parametros, string[] valores) {
            return base.Channel.GetBASE64Async(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetPemisionSectionsAccess(string[] Parametros, string[] valores) {
            return base.Channel.GetPemisionSectionsAccess(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPemisionSectionsAccessAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetPemisionSectionsAccessAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetPemisionAccess(string[] Parametros, string[] valores) {
            return base.Channel.GetPemisionAccess(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPemisionAccessAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetPemisionAccessAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetSectionRenderHtml(string[] Parametros, string[] valores) {
            return base.Channel.GetSectionRenderHtml(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetSectionRenderHtmlAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetSectionRenderHtmlAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetPlantillaCargaMasivaRender(string[] Parametros, string[] valores) {
            return base.Channel.GetPlantillaCargaMasivaRender(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetPlantillaCargaMasivaRenderAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetPlantillaCargaMasivaRenderAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetDownloadPlantillaCargaMasiva(string[] Parametros, string[] valores) {
            return base.Channel.GetDownloadPlantillaCargaMasiva(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetDownloadPlantillaCargaMasivaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetDownloadPlantillaCargaMasivaAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetObtenerEmpresas(string[] Parametros, string[] valores) {
            return base.Channel.GetObtenerEmpresas(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetObtenerEmpresasAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetObtenerEmpresasAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth GetBarcodes(string[] Parametros, string[] valores) {
            return base.Channel.GetBarcodes(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> GetBarcodesAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetBarcodesAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth SetEnrolarColaborador(string[] Parametros, string[] valores) {
            return base.Channel.SetEnrolarColaborador(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetEnrolarColaboradorAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetEnrolarColaboradorAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth SetControlErroresSistemas(string[] Parametros, string[] valores) {
            return base.Channel.SetControlErroresSistemas(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetControlErroresSistemasAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetControlErroresSistemasAsync(Parametros, valores);
        }
        
        public FiniquitosV2.ServicioAuth.ServicioAuth SetBatchChangeContrato(string[] Parametros, string[] valores) {
            return base.Channel.SetBatchChangeContrato(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioAuth.ServicioAuth> SetBatchChangeContratoAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetBatchChangeContratoAsync(Parametros, valores);
        }
    }
}
