//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiniquitosV2.ServicioSoftland {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioSoftland", Namespace="http://schemas.datacontract.org/2004/07/ServicioSoftland")]
    [System.SerializableAttribute()]
    public partial class ServicioSoftland : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet TableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSoftland.IServicioSoftland")]
    public interface IServicioSoftland {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetValidarPermitidoSolBj4", ReplyAction="http://tempuri.org/IServicioSoftland/GetValidarPermitidoSolBj4Response")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetValidarPermitidoSolBj4(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetValidarPermitidoSolBj4", ReplyAction="http://tempuri.org/IServicioSoftland/GetValidarPermitidoSolBj4Response")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetValidarPermitidoSolBj4Async(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetRutTrabajador", ReplyAction="http://tempuri.org/IServicioSoftland/GetRutTrabajadorResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetRutTrabajador(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetRutTrabajador", ReplyAction="http://tempuri.org/IServicioSoftland/GetRutTrabajadorResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetRutTrabajadorAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetListarContratosFiniquitados", ReplyAction="http://tempuri.org/IServicioSoftland/GetListarContratosFiniquitadosResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetListarContratosFiniquitados(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetListarContratosFiniquitados", ReplyAction="http://tempuri.org/IServicioSoftland/GetListarContratosFiniquitadosResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetListarContratosFiniquitadosAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetContratoActivoBaja", ReplyAction="http://tempuri.org/IServicioSoftland/GetContratoActivoBajaResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetContratoActivoBaja(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetContratoActivoBaja", ReplyAction="http://tempuri.org/IServicioSoftland/GetContratoActivoBajaResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetContratoActivoBajaAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetObtenerAreaNegocio", ReplyAction="http://tempuri.org/IServicioSoftland/GetObtenerAreaNegocioResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetObtenerAreaNegocio(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetObtenerAreaNegocio", ReplyAction="http://tempuri.org/IServicioSoftland/GetObtenerAreaNegocioResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetObtenerAreaNegocioAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetObtenerCargo", ReplyAction="http://tempuri.org/IServicioSoftland/GetObtenerCargoResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetObtenerCargo(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetObtenerCargo", ReplyAction="http://tempuri.org/IServicioSoftland/GetObtenerCargoResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetObtenerCargoAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetCentroCosto", ReplyAction="http://tempuri.org/IServicioSoftland/GetCentroCostoResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetCentroCosto(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetCentroCosto", ReplyAction="http://tempuri.org/IServicioSoftland/GetCentroCostoResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetCentroCostoAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNObtenerUsuario", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNObtenerUsuarioResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNObtenerUsuario(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNObtenerUsuario", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNObtenerUsuarioAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNAdicionalEnrolamiento", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNAdicionalEnrolamientoResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNAdicionalEnrolamiento(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNAdicionalEnrolamiento", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNAdicionalEnrolamientoResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNAdicionalEnrolamientoAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNEsJefatura", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNEsJefaturaResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNEsJefatura(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNEsJefatura", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNEsJefaturaResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNEsJefaturaAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNFicha", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNFichaResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNFicha(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNFicha", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNFichaResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNFichaAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasUsados", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasUsadosResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasUsados(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasUsados", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasUsadosResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasUsadosAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNContratoActivo", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNContratoActivoResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNContratoActivo(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNContratoActivo", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNContratoActivoResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNContratoActivoAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasPostTemp", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasPostTempResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasPostTemp(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasPostTemp", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasPostTempResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasPostTempAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasPendientes", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasPendientesResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasPendientes(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasPendientes", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasPendientesResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasPendientesAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasAdministrativos", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasAdministrativosResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasAdministrativos(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasAdministrativos", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasAdministrativosResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasAdministrativosAsync(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasAdicionales", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasAdicionalesResponse")]
        FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasAdicionales(string[] Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSoftland/GetVNDiasAdicionales", ReplyAction="http://tempuri.org/IServicioSoftland/GetVNDiasAdicionalesResponse")]
        System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasAdicionalesAsync(string[] Parametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSoftlandChannel : FiniquitosV2.ServicioSoftland.IServicioSoftland, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoftlandClient : System.ServiceModel.ClientBase<FiniquitosV2.ServicioSoftland.IServicioSoftland>, FiniquitosV2.ServicioSoftland.IServicioSoftland {
        
        public ServicioSoftlandClient() {
        }
        
        public ServicioSoftlandClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoftlandClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoftlandClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoftlandClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetValidarPermitidoSolBj4(string[] Parametros) {
            return base.Channel.GetValidarPermitidoSolBj4(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetValidarPermitidoSolBj4Async(string[] Parametros) {
            return base.Channel.GetValidarPermitidoSolBj4Async(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetRutTrabajador(string[] Parametros) {
            return base.Channel.GetRutTrabajador(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetRutTrabajadorAsync(string[] Parametros) {
            return base.Channel.GetRutTrabajadorAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetListarContratosFiniquitados(string[] Parametros) {
            return base.Channel.GetListarContratosFiniquitados(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetListarContratosFiniquitadosAsync(string[] Parametros) {
            return base.Channel.GetListarContratosFiniquitadosAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetContratoActivoBaja(string[] Parametros) {
            return base.Channel.GetContratoActivoBaja(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetContratoActivoBajaAsync(string[] Parametros) {
            return base.Channel.GetContratoActivoBajaAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetObtenerAreaNegocio(string[] Parametros) {
            return base.Channel.GetObtenerAreaNegocio(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetObtenerAreaNegocioAsync(string[] Parametros) {
            return base.Channel.GetObtenerAreaNegocioAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetObtenerCargo(string[] Parametros) {
            return base.Channel.GetObtenerCargo(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetObtenerCargoAsync(string[] Parametros) {
            return base.Channel.GetObtenerCargoAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetCentroCosto(string[] Parametros) {
            return base.Channel.GetCentroCosto(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetCentroCostoAsync(string[] Parametros) {
            return base.Channel.GetCentroCostoAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNObtenerUsuario(string[] Parametros) {
            return base.Channel.GetVNObtenerUsuario(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNObtenerUsuarioAsync(string[] Parametros) {
            return base.Channel.GetVNObtenerUsuarioAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNAdicionalEnrolamiento(string[] Parametros) {
            return base.Channel.GetVNAdicionalEnrolamiento(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNAdicionalEnrolamientoAsync(string[] Parametros) {
            return base.Channel.GetVNAdicionalEnrolamientoAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNEsJefatura(string[] Parametros) {
            return base.Channel.GetVNEsJefatura(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNEsJefaturaAsync(string[] Parametros) {
            return base.Channel.GetVNEsJefaturaAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNFicha(string[] Parametros) {
            return base.Channel.GetVNFicha(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNFichaAsync(string[] Parametros) {
            return base.Channel.GetVNFichaAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasUsados(string[] Parametros) {
            return base.Channel.GetVNDiasUsados(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasUsadosAsync(string[] Parametros) {
            return base.Channel.GetVNDiasUsadosAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNContratoActivo(string[] Parametros) {
            return base.Channel.GetVNContratoActivo(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNContratoActivoAsync(string[] Parametros) {
            return base.Channel.GetVNContratoActivoAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasPostTemp(string[] Parametros) {
            return base.Channel.GetVNDiasPostTemp(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasPostTempAsync(string[] Parametros) {
            return base.Channel.GetVNDiasPostTempAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasPendientes(string[] Parametros) {
            return base.Channel.GetVNDiasPendientes(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasPendientesAsync(string[] Parametros) {
            return base.Channel.GetVNDiasPendientesAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasAdministrativos(string[] Parametros) {
            return base.Channel.GetVNDiasAdministrativos(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasAdministrativosAsync(string[] Parametros) {
            return base.Channel.GetVNDiasAdministrativosAsync(Parametros);
        }
        
        public FiniquitosV2.ServicioSoftland.ServicioSoftland GetVNDiasAdicionales(string[] Parametros) {
            return base.Channel.GetVNDiasAdicionales(Parametros);
        }
        
        public System.Threading.Tasks.Task<FiniquitosV2.ServicioSoftland.ServicioSoftland> GetVNDiasAdicionalesAsync(string[] Parametros) {
            return base.Channel.GetVNDiasAdicionalesAsync(Parametros);
        }
    }
}
